blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('tips/', views.tips, name='tips'),
    path('archive/', views.archive, name='archive'),
    path('<int:blog_id>/', views.detail, name='detail'),    
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
import datetime
from django.db import models
from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    content = models.CharField(max_length=10000)
    posted = models.DateTimeField('date published')
      
    def short_post(self):
        x = self.content.split()
        s = x[:100]
        s = " ".join(s)
        return s
        
    def comment_count(self):
        return self.comment_set.count()
        
    def __str__(self):
        return self.content
        
class Comment(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)
    commenter = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.CharField(max_length=10000)
    posted = models.DateTimeField('date published')
        
    def __str__(self):
        return self.content

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms
from django.db import models
from .models import Blog, Comment

class CommentForm(forms.Form):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)
    commenter = forms.CharField(
        label="", 
        widget=forms.TextInput(attrs={'placeholder': 'Name'}),
        max_length=100,
        )
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
        )
    content = forms.CharField(
        label="", 
        widget=forms.Textarea(attrs={'placeholder': 'Say Something...',
                                    'style': 'resize:none',
                                    'rows': '5',
                                    'cols': '70',
                                    }), 
        max_length=10000,
        )
    
    posted = models.DateTimeField('date published')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Blog, Comment
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from .forms import CommentForm
import datetime

def index(request):
    recentBlogPosts = Blog.objects.order_by('-posted')[:3]
    context = { 'recentBlogPosts': recentBlogPosts,
    'myDate' : datetime.datetime.now(),
    }
    return render(request, 'blog/index.html', context)

def about(request):
    context = { 'myDate' : datetime.datetime.now(),
    }
    return render(request, 'blog/about.html', context)
    
def tips(request):
    context = { 'myDate' : datetime.datetime.now(),
    }
    return render(request, 'blog/tips.html', context)
    
def detail(request, blog_id):
    blogPost = get_object_or_404(Blog, pk=blog_id)
    get_comment = blogPost.comment_set.order_by('-posted')
    if request.method =='POST':
        form = CommentForm(request.POST)
        
        if form.is_valid():
            new_comment = Blog.objects.get(pk=blog_id)
            new_comment.comment_set.create(
                content = form.cleaned_data['content'],
                commenter = form.cleaned_data['commenter'],
                email = form.cleaned_data['email'],
                posted = datetime.datetime.now(),
                )
            new_comment.save()
            return HttpResponseRedirect('')
    else:
        form = CommentForm()
    
    context = {'get_comment': get_comment,
    'blog_id': blog_id,
    'myDate' : datetime.datetime.now(),
    'blogPost': blogPost,
    'form': form,
    }
    return render(request, 'blog/detail.html', context)

def archive(request):
    blog_posts = Blog.objects.order_by('-posted')
    context = {'blog_posts': blog_posts,
    'myDate': datetime.datetime.now(),
    }
    return render(request, 'blog/archive.html', context)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #redisplay voter form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

#Create your views here.

blog/templates/blog/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title>About Alex</title>
    </head>

    <body>
		<div id="container">
			<div id="header">
				<h1>About Alex</h1>
			</div>
				<div id="blog">
					<p><img src="{% static 'blog/images/alex.jpg' %}" alt="Alex" width=200 class='center'></p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum porta ante arcu, ultrices malesuada metus tincidunt a. Nunc quis consequat justo, et efficitur felis. 
					Nulla eu venenatis nisi. In odio magna, ornare at lacinia non, vestibulum molestie nunc. Morbi laoreet mauris sed ante hendrerit vestibulum. In et nibh quis leo ornare laoreet. 
					Nunc nisl nunc, tempus sit amet orci quis, eleifend egestas mauris. Nullam non sagittis tellus. Nulla posuere orci nec quam tincidunt pharetra. In sodales enim mauris, sed ultricies ligula egestas eu. 
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum porta ante arcu, ultrices malesuada metus tincidunt a. Nunc quis consequat justo, et efficitur felis. Nulla eu venenatis nisi. 
					In odio magna, ornare at lacinia non, vestibulum molestie nunc. Morbi laoreet mauris sed ante hendrerit vestibulum. In et nibh quis leo ornare laoreet. 
					Nunc nisl nunc, tempus sit amet orci quis, eleifend egestas mauris. Nullam non sagittis tellus. Nulla posuere orci nec quam tincidunt pharetra. In sodales enim mauris, sed ultricies ligula egestas eu. </p>
										
					<p>
							<img src="{% static 'blog/images/chicken.jpg' %}" alt="Grilled Chicken" height='200'>
					
							<img src="{% static 'blog/images/cat.jpg' %}" alt="Cute Kitten" height='275'>
						
							<img src="{% static 'blog/images/iceland.jpg' %}" alt="A trip to Iceland" height='200'>
					</p>
				</div>
				<div class="nav">
					<h2>Links</h2>
					<ul>
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a href="{% url 'blog:about' %}">About</a></li>
						<li><a href="{% url 'blog:archive' %}">Archive</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
		</div>
		
		


	
    </body>
</html>

blog/templates/blog/archive.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title>Archive</title>
    </head>

    <body>
		<div id="container">
			<div id="header">
				<h1>Archive</h1>
			</div>
				<div id="blog">
					{% if blog_posts %}
						<ul>
						{% for blogPost in blog_posts %}
						<!-- print blog title and content -->
							<h2><a href="{% url 'blog:detail' blogPost.id %}">{{ blogPost.title }}</a></h2>
							
							<p>{{ blogPost.short_post }}</p>
							<p>{{ blogPost.comment_count }} comments</p>
						{% endfor %}
						</ul>
					{% else %}
						<p>No blogs are available.</p>
					{% endif %}
				</div>
				<div class="nav">
					<h2>Links</h2>
					<ul id= "nav-links">
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a href="{% url 'blog:about' %}">About</a></li>
						<li><a href="{% url 'blog:archive' %}">Archive</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
		</div>
		
		


	
    </body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title>{{ blogPost.title }}</title>
    </head>

	<!-- Blog post detail view -->
    <body>
		<div id="container">
			<div id="header">
				<h1>Detail View</h1>
			
			<!-- /#Post and commnet form -->
			</div>
				<div id="blog">
					<h3>{{ blogPost.title }}</h3>
					<h5>By {{ blogPost.author }}</h5>
					<p>Posted {{blogPost.posted }}</p>
					<p>{{ blogPost.content }}</p>
					
					<!-- New comment form -->
					<h4>Leave a comment</h4>
					<form action="{% url 'blog:detail' blogPost.id %}" method="post">
					{% csrf_token %}
					{{ form.as_p }}
					<input type='submit' value='Comment'>
					</form>
					<!-- /#comment form -->
					
					<!-- Show comments -->
					<br>
					<h4>Comments</h4>
					{% if get_comment %}
						<ul>
						{% for comment in get_comment %}
						<!-- print blog title and content -->
							<h5>Comment by {{ comment.commenter }} at {{comment.posted }}</h5>
							<p>{{ comment }}</p>
						{% endfor %}
						</ul>
					{% else %}
						<p>No comments are available.</p>
					{% endif %}
				</div>

				<!-- Nav -->
				<div class="nav">
					<h2>Links</h2>
					<ul>
						<li><a id='links' href="{% url 'blog:index' %}">Home</a></li>
						<li><a id='links' href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a id='links' href="{% url 'blog:about' %}">About</a></li>
						<li><a id='links' href="{% url 'blog:archive' %}">Archive</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
				<!-- /#Nav -->
		</div>
		<!-- /#Blog post detail view -->
		
    </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title> </title>
    </head>

    <body>
		<div id="container">
			<div id="header">
				<h1>Home</h1>
			</div>
				<div id="blog">
					{% if recentBlogPosts %}
						<ul>
						{% for blogPost in recentBlogPosts %}
						<!-- print blog title and content -->
							<h2><a href="{% url 'blog:detail' blogPost.id %}">{{ blogPost.title }}</a></h2>
							<p>{{ blogPost.short_post }}</p>
							<p>{{ blogPost.comment_count }} comments</p>
						{% endfor %}
						</ul>
					{% else %}
						<p>No blogs are available.</p>
					{% endif %}
					
				</div>
				<div class="nav">
					<h2>Links</h2>
					<ul>
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a href="{% url 'blog:about' %}">About</a></li>
						<li><a href="{% url 'blog:archive' %}">Archive</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
		</div>
		
		


	
    </body>
</html>

blog/templates/blog/template.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title> </title>
    </head>

    <body>
		<div id="container">
			<div id="header">
				<h1> </h1>
			</div>
				<div id="blog">
					
				</div>
				<div class="nav">
					<h2>Links</h2>
					<ul>
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a href="{% url 'blog:about' %}">About</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
		</div>
		
		


	
    </body>
</html>

blog/templates/blog/tips.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'blog/style/style.css' %}" type="text/css"/>
        <title>Alex's Tips</title>
    </head>

    <body>
		<div id="container">
			<div id="header">
				<h1>Tech Tips from Alex</h1>
			</div>
				<div id="blog">
					
					<p id="tipFormat">
						<h3>Bash Command Tip</h3>
						<ol>
							<li>cd</li>
							<li>This command allows you to change the directory that you are accessing.</li>
							<li><code>cd cs2610-price-alex-assn0</code></li>
						</ol>
					</p>
					<p id="tipFormat">
						<h3>Git Command Tip</h3>
						<ol>
							<li>status</li>
							<li>This command will display the status of your repository, meaning you can see which files have been added to be updated on your next commit.</li>
							<li><code>git status</code></li>
						</ol>
					</p>
					<p id="tipFormat">
						<h3>HTML Tag Tip</h3>
						<ol>
							<li>title</li>
							<li>The title tag changes what your browser displays at the top of the browswer window and on the tab of the webpage.</li>
							<li><code>&lt;title&gt; Alex's Blog &lt;/title&gt;</code></li>
						</ol>
					</p>
					<p id="tipFormat">
						<h3>CSS Concept Tip</h3>
						<ol>
							<li>#id</li>
							<li>This allows you to specify which part of your html to modify by using the name of the "div".</li>
							<li><code>#container{}</code></li>
						</ol>
					</p>
				</div>
				<div class="nav">
					<h2>Links</h2>
					<ul>
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="{% url 'blog:tips' %}">Tips</a></li>						
						<li><a href="{% url 'blog:about' %}">About</a></li>
						<li><a href="{% url 'blog:archive' %}">Archive</a></li>
					</ul>
					<p></p>
					<p>{{ myDate|date:"DATE_FORMAT" }} </p>
					<p>{{ myDate|time:"h:i:s A" }}</p>
				</div>
		</div>
		
		
		


	
    </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>